apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neo4j
commonAnnotations:
  application: neo4j-standalone
resources:
  - namespace.yaml
  - nginx-ingress.yaml
  - neo4j-source.yaml
  - client-one.yaml
  - client-two.yaml
  - tls-provider.yaml