apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: neo4j-nginx
spec:
  interval: 30m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: neo4j-nginx
        namespace: neo4j
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "false"  #set to true for internal load balancer
      ingressClassResource:
        # -- Name of the ingressClass
        name: neo4j-nginx # -- This is the name of the ingressClass resource. Make sure it does not interfere with other ingressClass resources
        controllerValue: "k8s.io/neo4j-ingress-nginx"
        # -- Is this ingressClass enabled or not
        enabled: true
      ingressClass: neo4j-nginx
    tcp:  # -- TCP services. Add a new pair for each nw client: port and service name
      '9001': 'neo4j/client-one-lb-neo4j:7687'
      '9002': 'neo4j/client-two-lb-neo4j:7687'



